# Generated by Django 5.0.2 on 2024-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='category',
            field=models.CharField(choices=[('security', 'Security'), ('restaurants', 'Restaurants'), ('bathrooms', 'Bathrooms'), ('general', 'General'), ('amenities', 'Amenities'), ('accessibility', 'Accessibility')]),
        ),
    ]
