# Generated by Django 5.0.2 on 2024-02-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_airport'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
