# Generated by Django 5.0.2 on 2024-02-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_reviews_review'),
        ('backend_api', '0004_airport_name'),
    ]

    operations = [
    ]
