# Generated by Django 5.0.2 on 2024-02-09 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_review_airport_review_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
