# Generated by Django 5.0.2 on 2024-02-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0008_alter_review_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('Security', 'Security'), ('Restaurants', 'Restaurants'), ('Bathrooms', 'Bathrooms'), ('General', 'General'), ('Amenities', 'Amenities'), ('Accessibility', 'Accessibility')], max_length=50),
        ),
    ]
